# Mercenary Guilds

## Fighter's Guilds

### The Swords of the Solar

Lead by redhead Aasimar, takes on all skill levels and turns them into fierce fighters

### The Hunter's Guild

Biomancy enhanced strength, bigger and unique weapons from MH series

### Ranger's Guilds [Need a better name]

Guides, trackers and investigators (e.g. "witch hunter" archetype)

### Expeditionists Guild

incl. cartographers, basically explorers who specifically delve and map uncharted territory

### Retinue / security Guild [Needs better name]

Guards, and military contracts to work for nobles and knights

### Mariner's Guild

Boat crew, also a bunch of boat related services

## Staffer's Guilds

### Heralds

Those skilled in both presenting nobles, heraldry, courtly affairs, and the administrative side of nobility, in addition to military training

### Messengers

long distance comms, obviously

### Navigators

Swashbucklers and trade route specialists, also with a keen eye for strategy around protecting cargo

### Bards

Token musical guild
